#!/bin/bash
#   lxdm-login Version 2.0.1
#   Sept 07, 2012
#
#   Bodhi Linux (c) 2012
#   Authors : rbt y-lee <ylee@bodhilinux.com>
#             Jeff Hoogland <JeffHoogland@Linux.com>
#   Special Thanks: Vivek Gite for his listusers.bash script
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>
#

_l="/etc/login.defs"
_p="/etc/passwd"

# get mini UID limit ##
MIN_UID=$(grep "^UID_MIN" $_l)

# get max UID limit ##
MAX_UID=$(grep "^UID_MAX" $_l)

USERLIST=$(awk -F':' -v "min=${MIN_UID##UID_MIN}" -v "max=${MAX_UID##UID_MAX}" '{ if ( $3 >= min && $3 <= max  && $7 != "/sbin/nologin" ) print "FALSE", $1}' "$_p")

username=$(zenity --window-icon=/usr/share/icons/bodhi.png --list --title lxdm-login --text "Select user to be automatically logged in " --radiolist --column "" --column "User" TRUE None ${USERLIST[@]})

if [ $? -eq 1 ]; then
  # User canceled exit 0 to avoid e17 error dialog
  exit 0
fi

if [ "$username" == "None" ]
then
  username=""
fi

echo $username

cp -p --force /etc/lxdm/default.conf /etc/lxdm/default.backup

difference=`diff /etc/lxdm/default.conf /etc/lxdm/default.backup`

if [ "$difference" ]
then
  cp -p --force /etc/lxdm/lxdm.conf /etc/lxdm/default.conf
  echo "autologin=$username" >> /etc/lxdm/default.conf
  echo "LXDM default.conf replaced."
else
  echo "lxdm-login: Error in making backup!" 1>&2
fi

# exit 0 even on error above to avoid e17 error dialog
exit 0
